Add code to confirm that procedures are available when referenced by SRM.

diff --git a/test/test_site b/test/test_site
--- a/test/test_site
+++ b/test/test_site
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 declare shost="schemaserver_test"
+declare srmfile="$1"
 
 declare -a comyad=(
     --title "wget result"
@@ -17,12 +18,59 @@ declare -a comopts=(
 declare -a options pdata yadopts
 declare xmlresult
 
+get_srm_database()
+{
+    echo "SchemaServer_Test"
+}
+
+
+confirm_proc_exists()
+{
+    local proc_name="$1"
+    local -i pcount=0
+    local query="\
+SELECT COUNT(*)
+  FROM ROUTINES \
+ WHERE ROUTINE_SCHEMA='${DBNAME}' \
+   AND ROUTINE_NAME='${proc_name}'"
+ 
+    pcount=$( mysql -Ns information_schema -e "${query}" )
+
+    # Ending with test "returns" the test result:
+    [ $pcount -ne 0 ]
+}
+
+confirm_referenced_procedures()
+{
+    declare DBNAME=$( get_srm_database )
+    local -i missing=0
+
+    local -a procs_array
+    procs_array=( $( awk -F ":" '/schema-proc|procedure/ { print $2 }' "$srmfile" | sort -u - ) )
+
+    local proc
+    for proc in "${procs_array[@]}"; do
+        if ! confirm_proc_exists "$proc"; then
+            (( missing++ ))
+            echo "Procedure '$proc' is missing."
+        fi
+    done
+
+    if [ $missing -eq 0 ]; then
+        echo "No references procedures are missing."
+    else
+        echo "There are $missing missing procedures."
+    fi
+
+    return $missing
+}
+
 
 show_default_page()
 {
     local -a options yadopts
     local xmlresult
-    options=( "http://localhost/Person.srm" "${comopts[@]}" )
+    options=( "http://localhost/${srmfile}" "${comopts[@]}" )
     xmlresult=$( wget "${options[@]}" )
     yadopts=( "${comyad[@]}" $( echo "${xmlresult}" | xsltproc test.xsl - ) )
     yad "${yadopts[@]}"
@@ -32,7 +80,7 @@ show_add_item_page()
 {
     local -a options yadopts pdata
     local xmlresult
-    options=( "http://localhost/Person.srm?add" "${comopts[@]}" )
+    options=( "http://localhost/${srmfile}?add" "${comopts[@]}" )
     pdata=( "add" )
     xmlresult=$( wget "${options[@]}" --post-data="${pdata[*]}" )
     echo "${xmlresult}"
@@ -41,6 +89,13 @@ show_add_item_page()
     echo "${yadopts[@]}"
     yad "${yadopts[@]}"
 }
+
+
+confirm_referenced_procedures
+if [ $? -ne 0 ]; then
+    echo "Terminating test."
+    exit 1
+fi
 
 show_add_item_page
 show_default_page
